#!/usr/bin/env ruby

DOTROOT = __dir__

def ohai(*args)
  print "\r\033[2K  [ \033[0;34m..\033[0m ] ", *args, "\n"
end

def ok(*args)
  print "\r\033[2K  [ \033[1;32mOK\033[0m ] ", *args, "\n"
end

def fail(*args)
  print "\r\033[2K  [\033[0;31mFAIL\033[0m] ", *args, "\n"
  exit
end

def ask(question, default = '')
  printf "\r\033[2K  [ \033[0;33m??\033[0m ] #{question} "
  printf "[ #{default} ] " if default != ''
  val = gets.chomp
  return val != '' ? val : default
end

def os
  # RUBY_PLATFORM will say 'java' on JRuby regardless of host OS it is running on
  # but it's okay for us.
  case RUBY_PLATFORM
  when /darwin/
    :macos
  else
    raise "unknown os"
  end
end

def cmd_exists?(cmd)
  result = `which #{cmd}`
  return result != ''
end

def install(filename)
  filename = "#{filename}/install.rb" if filename.is_a? Symbol
  filename = "#{DOTROOT}/#{filename}"
  if filename and File.exists? filename
    ohai "Run #{filename}"
    case File.extname(filename)
    when '.rb'; eval File.read(filename)
    when '.sh'; print `DOTROOT="#{DOTROOT}" sh -c "#{filename}"`
    end
  end
end

def shell(cmd)
  puts "$ #{cmd}"
  system cmd
end

def link
  Dir.glob("#{DOTROOT}/**/*.symlink").each do |src|
    dst = File.join(Dir.home, ".#{File.basename(src).gsub(/\.symlink$/, '')}")
    unless File.exists? dst
      ohai "Link #{src} to #{dst}"
      `ln -s "#{src}" "#{dst}"`
    end
  end
end

if __FILE__ == $0
  require "#{DOTROOT}/recipe.rb"
  link
end
