language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

sudo: false

os:
  - linux
  - osx

language: go

go:
  - 1.6

env:
  global:
    - APM_TEST_PACKAGES="environment go-config go-get autocomplete-go gofmt navigator-godef tester-go gorename gometalinter-linter linter"

  matrix:
    - ATOM_CHANNEL=beta
    - ATOM_CHANNEL=stable

script:
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u sourcegraph.com/sqs/goreturns
  - go get -u github.com/rogpeppe/godef
  - go get -u github.com/nsf/gocode
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
