#!/bin/sh

brew cask install 1password
brew cask install appcleaner
brew cask install atom
brew cask install bettertouchtool
brew cask install bittorrent-sync
brew cask install dropbox
brew cask install evernote
brew cask install google-chrome
brew cask install google-drive
brew cask install iterm2
brew cask install the-unarchiver
brew cask install tower
