notifications:
  email:
    on_success: never
    on_failure: change

sudo: false

os:
  - linux
  - osx

language: go

go:
  - 1.6

env:
  global:
    - APM_TEST_PACKAGES="environment"
    - ATOM_ACCESS_TOKEN=da809a6077bb1b0aa7c5623f7b2d5f1fec2faae4

  matrix:
    - ATOM_CHANNEL=beta
    - ATOM_CHANNEL=stable

script:
  - 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
